// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-4_FjcPW8gqs_q5rfWfgTHGkrlkJ4opc',
    appId: '1:235191014627:web:fec47adc3e3657b5b7a1d6',
    messagingSenderId: '235191014627',
    projectId: 'fbshop-pro',
    authDomain: 'fbshop-pro.firebaseapp.com',
    storageBucket: 'fbshop-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIc3N9_U7uE3528LVoX16hv_36s-4myyc',
    appId: '1:235191014627:android:2c1c88e6c7678094b7a1d6',
    messagingSenderId: '235191014627',
    projectId: 'fbshop-pro',
    storageBucket: 'fbshop-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXFk7J1urpzEGLJ97-QAwPcSK7FhF7zYM',
    appId: '1:235191014627:ios:b4b26aa9a5afbb62b7a1d6',
    messagingSenderId: '235191014627',
    projectId: 'fbshop-pro',
    storageBucket: 'fbshop-pro.appspot.com',
    iosBundleId: 'pro.smartapps.shopbloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXFk7J1urpzEGLJ97-QAwPcSK7FhF7zYM',
    appId: '1:235191014627:ios:8791d29382f2a3cfb7a1d6',
    messagingSenderId: '235191014627',
    projectId: 'fbshop-pro',
    storageBucket: 'fbshop-pro.appspot.com',
    iosBundleId: 'com.example.shopFblock.RunnerTests',
  );
}
